name: Opdex-UI
trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  location: 'Central US'
  azureSubscription: 'sub-opdex-dev'
  ARTIFACT_NAME: platform-api
  artifactName: ReleaseArtifact
  releaseTemplate: 'azure-pipelines.release.yml'

stages:
- stage: CI
  displayName: 'Continuous Integration'

  jobs:
  - job: Build
    displayName: Build and Publish

    variables:
      SOLUTION: 'Opdex.sln'
      BUILD_CONFIGURATION: 'Release'
    
    steps:

      - task: NodeTool@0
        inputs:
          versionSpec: '14.x'
        displayName: 'Install Node.js'

      - script: |
          npm install
          npm run build-devnet
        displayName: 'npm install and build'

        # Does this syntax run on Azure DevOps?
      - name: Build
        run: |
          npm install
          npm run build-devnet
 
      - task: ArchiveFiles@2
        displayName: 'Archive files'
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/dist/out-tsc'
          includeRootFolder: false
          archiveType: zip
          archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
          replaceExistingArchive: true

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          ArtifactName: 'drop'
          publishLocation: 'Container'

      # - task: PublishBuildArtifacts@1
      #   inputs:
      #     pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
      #     artifactName: '$(ARTIFACT_NAME)'
      #   displayName: Share

- stage: DEV
  displayName: 'Release to devnet (Azure)'
  dependsOn: CI
  jobs:
  - template: ${{ variables.releaseTemplate }}
    parameters:
      environment: 'dev'

- stage: TEST
  displayName: 'Release to testnet (Azure)'
  dependsOn: DEV
  jobs:
  - template: ${{ variables.releaseTemplate }}
    parameters:
      environment: 'test'

- stage: MAIN
  displayName: 'Release to mainnet (Azure)'
  dependsOn: TEST
  jobs:
  - template: ${{ variables.releaseTemplate }}
    parameters:
      environment: 'main'
