parameters:
- name: environment
  type: string

jobs:
  - deployment: ${{ parameters.environment }}
    displayName: 'Deploy Resources'
    variables:
      - group: '${{ parameters.environment }}-ui' # points to variable group in Azure DevOps
    environment: ${{ parameters.environment }} # points to environments in Azure DevOps
    strategy:
      runOnce:
        deploy:
          steps:
            - task: replacetokens@3
              inputs:
                targetFiles: '$(Pipeline.Workspace)/$(ARTIFACT_NAME)/**/main*.js'
                encoding: 'auto'
                writeBOM: true
                verbosity: 'detailed'
                actionOnMissing: 'warn'
                keepToken: false
                tokenPrefix: '#{'
                tokenSuffix: '}#'
                useLegacyPattern: false
                enableTelemetry: true

            - task: ArchiveFiles@2
              displayName: 'Archive files'
              inputs:
                rootFolderOrFile: '$(Pipeline.Workspace)/$(ARTIFACT_NAME)'
                includeRootFolder: false
                archiveType: zip
                archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
                replaceExistingArchive: true

            - task: PublishBuildArtifacts@1
              inputs:
                PathToPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
                ArtifactName: '$(ARTIFACT_NAME)'
                publishLocation: 'Container'

            - task: AzureWebApp@1
              inputs:
                azureSubscription: $(azureSubscription)
                appType: 'webApp'
                appName: 'app-opdex-${{ parameters.environment }}-app'
                package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
                deploymentMethod: 'auto'
              displayName: Deploy to App Service
